spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes_service
    username: anas
    password: root
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080
