spring:
  config:
    activate:
      on-profile: test
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect