name: Run Unit Tests

on:
  push:
    branches: [main, develop]  # Runs tests on push to main or develop
  pull_request:
    branches: [main, develop]  # Runs tests on PRs to main or develop

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out the code

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Uses Eclipse Temurin JDK
          java-version: '23'  # Matches Java 23 from your logs
          cache: 'gradle'  # Caches Gradle dependencies

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x recipeService/gradlew

      - name: Run Unit Tests
        working-directory: recipeService  # ✅ Set working directory to `recipeService`
        run: ./gradlew test

      - name: Upload Test Results (Optional)
        if: failure()  # Runs only if tests fail
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: test-reports
          path: recipeService/build/reports/tests/  # ✅ Updated path
          compression-level: 9  # Higher compression for smaller artifacts

      - name: Fail Workflow on Test Failure
        if: failure()
        run: exit 1  # Forces the workflow to fail if tests fail